require("XML")
doc <- htmlParse("m49alpha.htm")
out <- xpathSApply(doc, "//table[2]//tr//td", xmlValue)
pos <- tail(grep("ISO ALPHA-3", out), n = 1L)
out <- sub("^[[:space:]]*", "", out[-seq <- len(pos)])
out <- sub("[[:space:]]*$", "", out)
